# Generated by Django 4.0.5 on 2022-07-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursotecnologico',
            old_name='numeroRTa',
            new_name='numeroRT',
        ),
    ]
