# Generated by Django 4.0.5 on 2022-07-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_initial'),
        ('recurso', '0002_estado_reservable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursotecnologico',
            name='turnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turno', to='mantenimiento.turno'),
        ),
    ]
