# Generated by Django 4.0.5 on 2022-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('diaSemana', models.CharField(max_length=20)),
                ('fechaHoraInicio', models.DateTimeField(null=True)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_turno_actual', to='recurso.cambioestadort')),
                ('cambioEstadoTurno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_estado_Turno', to='recurso.cambioestadort')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turno', to='recurso.recursotecnologico')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
