# Generated by Django 4.0.5 on 2022-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('diaSemana', models.CharField(max_length=20)),
                ('fechaHoraInicio', models.DateTimeField(null=True)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
