# Generated by Django 4.0.5 on 2022-07-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0001_initial'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_turno_actual', to='recurso.cambioestadort'),
        ),
        migrations.AddField(
            model_name='turno',
            name='cambioEstadoTurno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambio_estado_Turno', to='recurso.cambioestadort'),
        ),
    ]
