# Generated by Django 4.0.5 on 2022-07-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
        ('mantenimiento', '0003_cambioestadoturno_alter_turno_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField(null=True)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraInicioPrevista', models.DateTimeField(null=True)),
                ('motivoMantenimiento', models.CharField(max_length=500, null=True)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurso_mantenimiento', to='recurso.recursotecnologico')),
            ],
            options={
                'verbose_name_plural': 'Mantenimiento',
            },
        ),
    ]
