# Generated by Django 4.0.5 on 2022-07-05 14:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('legajo', models.CharField(max_length=50, null=True)),
                ('correoElectronicoInstitucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('correoElectronicoPersonal', models.EmailField(blank=True, max_length=254, null=True)),
                ('numeroDocumento', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Por favor seleccione un número de documento válido.', regex='^[0-9]{7,9}$')])),
                ('telefonoCelular', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Por favor seleccione un número de teléfono válido.', regex='^[0-9]{7,10}$')])),
                ('fechaAlta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PersonalCientifico',
            },
        ),
        migrations.CreateModel(
            name='AsignacionResponsableTecnicoRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateTimeField(blank=True, null=True)),
                ('fechaHasta', models.DateTimeField(blank=True, null=True)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='personal.personalcientifico')),
                ('recursos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurso_tecnologico', to='recurso.recursotecnologico')),
            ],
            options={
                'verbose_name_plural': 'AsignacionResponsableTecnicoRT',
            },
        ),
    ]
