# Generated by Django 4.0.5 on 2022-07-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionresponsabletecnicort',
            options={'verbose_name_plural': 'AsignacionResponsableTecnicoRT'},
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='correoElectronicoInstitucional',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='correoElectronicoPersonal',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='fechaAlta',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='legajo',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='numeroDocumento',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='telefonoCelular',
        ),
        migrations.RemoveField(
            model_name='asignacionresponsabletecnicort',
            name='usuario',
        ),
        migrations.AddField(
            model_name='asignacionresponsabletecnicort',
            name='fechaDesde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionresponsabletecnicort',
            name='fechaHasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
